"""Pre-reveal tests for the diagnostic beta/volume-sensitive Cl topology."""

from __future__ import annotations

import inspect
import unittest

import numpy as np

from modern_full_model.parameters import PhysicalConstants
from modern_full_model.vbeta_diagnostic import (
    CAPACITY_EVIDENCE_STATUS,
    VbetaParameters,
    VbetaTopology,
    assess_pre_vbeta_trajectory,
    evaluate_vbeta_current,
    vbeta_effective_conductance_S,
)


class TestVbetaNestedTopology(unittest.TestCase):
    def setUp(self) -> None:
        self.constants = PhysicalConstants()
        self.common = {
            "beta_input": 1.0,
            "cell_volume_pL": 1.3,
            "v_apical_V": -0.060,
            "chloride_cell_mM": 50.0,
            "chloride_lumen_mM": 130.0,
            "thermal_voltage_V": self.constants.thermal_voltage_V,
            "faraday_C_mol": self.constants.faraday_C_mol,
        }

    def test_v0_is_an_exact_zero_current_control(self) -> None:
        # A deliberately enormous unused gV proves exact topology nesting.
        parameters = VbetaParameters(
            topology=VbetaTopology.V0_EXACT_CONTROL,
            maximum_conductance_S=1.0,
            reference_cell_volume_pL=1.0,
        )
        result = evaluate_vbeta_current(
            parameters,
            **{**self.common, "cell_volume_pL": 1.5},
        )
        self.assertEqual(result.effective_conductance_S, 0.0)
        self.assertEqual(result.current_A, 0.0)
        self.assertEqual(result.chloride_cell_source_fmol_s, 0.0)
        self.assertEqual(result.chloride_lumen_source_fmol_s, 0.0)

    def test_v1_gate_is_zero_at_rest_during_shrinkage_or_without_beta(self) -> None:
        parameters = VbetaParameters(
            topology=VbetaTopology.V1_RECTIFIED_SWELLING_GATE,
            maximum_conductance_S=31.4e-9,
            reference_cell_volume_pL=1.3,
        )
        for beta, volume in ((1.0, 1.3), (1.0, 1.2), (0.0, 1.5)):
            with self.subTest(beta=beta, volume=volume):
                self.assertEqual(
                    vbeta_effective_conductance_S(
                        parameters,
                        beta_input=beta,
                        cell_volume_pL=volume,
                    ),
                    0.0,
                )

    def test_v1_implements_the_predeclared_rectified_conductance(self) -> None:
        parameters = VbetaParameters(
            topology=VbetaTopology.V1_RECTIFIED_SWELLING_GATE,
            maximum_conductance_S=20.0e-9,
            reference_cell_volume_pL=1.0,
        )
        self.assertAlmostEqual(
            vbeta_effective_conductance_S(
                parameters,
                beta_input=0.5,
                cell_volume_pL=1.125,
            ),
            1.25e-9,
            places=22,
        )

    def test_v1_current_preserves_chloride_and_charge_exactly(self) -> None:
        parameters = VbetaParameters(
            topology=VbetaTopology.V1_RECTIFIED_SWELLING_GATE,
            maximum_conductance_S=20.0e-9,
            reference_cell_volume_pL=1.0,
        )
        result = evaluate_vbeta_current(
            parameters,
            **{**self.common, "cell_volume_pL": 1.125},
        )
        self.assertNotEqual(result.current_A, 0.0)
        self.assertLess(abs(result.chloride_conservation_residual_fmol_s), 1.0e-15)
        self.assertLess(abs(result.charge_conversion_residual_fmol_s), 1.0e-15)
        self.assertFalse(result.production_eligible)
        self.assertEqual(result.capacity_evidence_status, CAPACITY_EVIDENCE_STATUS)


class TestVbetaExactRestAntiDeadlock(unittest.TestCase):
    def test_existing_ipr_only_pre_vbeta_shrinkage_rejects_v1(self) -> None:
        # Reproduced from the exact resting WT reference with R1 tau=30 s,
        # resting Ca=0.058 uM, and an IPR/beta step.  The complete reproducible
        # trajectory is generated by the companion diagnostic runner; these
        # landmarks lock the decisive direction without slowing unit tests.
        volume = np.asarray((1.3, 1.299985636214203, 1.299265164921461, 1.2737304840985098))
        beta = np.asarray((0.0, 1.0, 1.0, 1.0))
        result = assess_pre_vbeta_trajectory(
            volume,
            beta,
            reference_cell_volume_pL=1.3,
        )
        self.assertEqual(result.status, "REJECTED_EXACT_REST_ANTI_DEADLOCK")
        self.assertTrue(result.exact_rest_initialization)
        self.assertEqual(result.maximum_relative_swelling, 0.0)
        self.assertEqual(result.maximum_rectified_gate, 0.0)
        self.assertFalse(result.activation_detected)
        self.assertFalse(result.usable_rescue)
        self.assertFalse(result.production_eligible)
        self.assertIn(
            "NO_PRE_VBETA_SWELLING_TO_OPEN_ONE_SIDED_GATE",
            result.rejection_reasons,
        )

    def test_exogenous_swelling_only_opens_a_production_ineligible_probe(self) -> None:
        result = assess_pre_vbeta_trajectory(
            (1.3, 1.35, 1.4625),
            (0.0, 1.0, 1.0),
            reference_cell_volume_pL=1.3,
        )
        self.assertEqual(
            result.status,
            "DIAGNOSTIC_GATE_OPENS_BUT_CAPACITY_UNLICENSED",
        )
        self.assertTrue(result.activation_detected)
        self.assertAlmostEqual(result.maximum_relative_swelling, 0.125)
        self.assertFalse(result.usable_rescue)
        self.assertFalse(result.production_eligible)

    def test_nonrest_initialization_cannot_evade_the_gate(self) -> None:
        result = assess_pre_vbeta_trajectory(
            (1.31, 1.32),
            (0.0, 1.0),
            reference_cell_volume_pL=1.3,
        )
        self.assertEqual(
            result.status,
            "REJECTED_INVALID_ANTI_DEADLOCK_INITIALIZATION",
        )
        self.assertFalse(result.exact_rest_initialization)
        self.assertFalse(result.usable_rescue)

    def test_module_is_heldout_free_and_has_no_source_class_specific_branch(self) -> None:
        import modern_full_model.vbeta_diagnostic as module

        source = inspect.getsource(module).casefold()
        self.assertNotIn("heldout_targets", source)
        self.assertNotIn("ae4_null", source)
        self.assertNotIn("n_abs", source)
        self.assertNotIn("an_abs", source)


if __name__ == "__main__":
    unittest.main()
